### ISSUE TITLE
Add `rpng` to _Compared to competitors_ web section

### ISSUE THREAD

**Issue by raysan5** [nayuki/PNG-library#2]
Hi! Just came to this repo while looking for a QR generation library and found your projects and your web. Congratulations, it's an amazing work.

Some time ago I created [`rpng`](https://github.com/raysan5/rpng/tree/master), it's a single-file header-only portable PNG chunks reader/writer, also supports PNG reading/writing and embeds a DEFLATE implementation, coded in C. All in about 3000 lines of code.

I thought it could be added to the comparison list.

**Comment by nayuki** [comment]
Based on your description, that seems relevant! I added it to my review queue. Cheers.

**Comment by raysan5** [comment]
Thank you very much! 😄
